#' @title Process Qualtrics Data Files
#'
#' @description This function reads in and processes a series of CSV files
#' exported from Qualtrics. It assumes the first two rows of each file contain
#' metadata and not actual data.
#'
#' @param data_files A character vector of file paths to the CSV files to be
#' processed.
#' @param rename_files Logical. If TRUE, the data and labels for each file will
#' be saved under a new name based on the original file name. Default is FALSE.
#' @param new_names A character vector of new names for the files. This should
#' be the same length as data_files. If NULL and rename_files is TRUE, new names
#' will be generated by removing the timestamp and anything before it from the
#' original file name. Default is NULL.
#'
#' @return This function does not return anything. It writes processed data and
#' labels to CSV files and assigns the resulting data frames to new variables in
#' the global environment.
#' @references Remember to add reference here
#' @export
#' @examples
#' \dontrun{
#' process_qualtrics_files(c("file1.csv", "file2.csv"), rename_files = TRUE, new_names = c("survey1", "survey2"))
#' }



process_qualtrics_files <- function(data_files, rename_files = FALSE, new_names = NULL) {
  # If rename_files is FALSE or not provided, use the original file names
  if (!rename_files) {
    new_names <- tolower(gsub("\\.csv$", "", basename(data_files)))
  }
  # If rename_files is TRUE but no new_names list is provided, create new names
  else if (is.null(new_names)) {
    new_names <- tolower(gsub(".+\\+-+(.+?)_.+", "\\1", basename(data_files)))
  }

  for (i in seq_along(data_files)) {
    file <- data_files[i]
    new_name <- new_names[i]
    data <- read.csv(file, na.strings = c("", "NA", "N/A"), header = TRUE)

    # Extract labels and clean data directly within the loop
    labels <- data[1, ]
    cleaned_data <- data[-(1:2),]

    # Save and reload the cleaned data and labels directly within the loop
    filename_data <- paste0('data_', gsub('\\W', '', tolower(new_name)), '.csv')
    filename_labels <- paste0('labels_data_', gsub('\\W', '', tolower(new_name)), '.csv')

    write.csv(cleaned_data, filename_data, na = "")
    write.csv(labels, filename_labels, na = "")

    cleaned_data <- read.csv(filename_data, na.strings = c("", "NA", "N/A"), header = TRUE)
    labels <- read.csv(filename_labels, na.strings = c("", "NA", "N/A"), header = TRUE)

    # Assign the cleaned data and labels to new objects in the global environment
    assign(paste0('data_', gsub('\\W', '', tolower(new_name))), cleaned_data, envir = .GlobalEnv)
    assign(paste0('labels_data_', gsub('\\W', '', tolower(new_name))), labels, envir = .GlobalEnv)
  }
}
